// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_local_user

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timetypes/timetypes"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func LocalUserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_expires": schema.StringAttribute{
				CustomType:          timetypes.RFC3339Type{},
				Computed:            true,
				Description:         "The time where the local user account expires.",
				MarkdownDescription: "The time where the local user account expires.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the local user.",
				MarkdownDescription: "The description of the local user.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "The status of the local user.",
				MarkdownDescription: "The status of the local user.",
			},
			"full_name": schema.StringAttribute{
				Computed:            true,
				Description:         "The full name of the local user.",
				MarkdownDescription: "The full name of the local user.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the retrieved local user. This is the same as the SID.",
				MarkdownDescription: "The ID of the retrieved local user. This is the same as the SID.",
			},
			"last_logon": schema.StringAttribute{
				CustomType:          timetypes.RFC3339Type{},
				Computed:            true,
				Description:         "The last logon time of the local user.",
				MarkdownDescription: "The last logon time of the local user.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Description:         "The name of the local user. Exactly one of 'name' or 'sid' is required.",
				MarkdownDescription: "The name of the local user. Exactly one of 'name' or 'sid' is required.",
			},
			"password_changeable_date": schema.StringAttribute{
				CustomType:          timetypes.RFC3339Type{},
				Computed:            true,
				Description:         "The password changeable date of the local user.",
				MarkdownDescription: "The password changeable date of the local user.",
			},
			"password_expires": schema.StringAttribute{
				CustomType:          timetypes.RFC3339Type{},
				Computed:            true,
				Description:         "The time when the password of the local user expires.",
				MarkdownDescription: "The time when the password of the local user expires.",
			},
			"password_last_set": schema.StringAttribute{
				CustomType:          timetypes.RFC3339Type{},
				Computed:            true,
				Description:         "The last time when the password was set for the local user.",
				MarkdownDescription: "The last time when the password was set for the local user.",
			},
			"password_required": schema.BoolAttribute{
				Computed:            true,
				Description:         "If true a password is required login with the local user.",
				MarkdownDescription: "If true a password is required login with the local user.",
			},
			"sid": schema.StringAttribute{
				Optional:            true,
				Description:         "The security ID of the local user. Exactly one of 'name' or 'sid' is required.",
				MarkdownDescription: "The security ID of the local user. Exactly one of 'name' or 'sid' is required.",
			},
			"user_may_change_password": schema.BoolAttribute{
				Computed:            true,
				Description:         "If true the local user can change it's password.",
				MarkdownDescription: "If true the local user can change it's password.",
			},
		},
		Description:         "Retrieve information about a local user. You can get a user by the name or the security ID.",
		MarkdownDescription: "Retrieve information about a local user. You can get a user by the name or the security ID.",
	}
}

type LocalUserModel struct {
	AccountExpires         timetypes.RFC3339 `tfsdk:"account_expires"`
	Description            types.String      `tfsdk:"description"`
	Enabled                types.Bool        `tfsdk:"enabled"`
	FullName               types.String      `tfsdk:"full_name"`
	Id                     types.String      `tfsdk:"id"`
	LastLogon              timetypes.RFC3339 `tfsdk:"last_logon"`
	Name                   types.String      `tfsdk:"name"`
	PasswordChangeableDate timetypes.RFC3339 `tfsdk:"password_changeable_date"`
	PasswordExpires        timetypes.RFC3339 `tfsdk:"password_expires"`
	PasswordLastSet        timetypes.RFC3339 `tfsdk:"password_last_set"`
	PasswordRequired       types.Bool        `tfsdk:"password_required"`
	Sid                    types.String      `tfsdk:"sid"`
	UserMayChangePassword  types.Bool        `tfsdk:"user_may_change_password"`
}
