// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package local_resources

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LocalGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Required:            true,
				Description:         "Define a description for the local security group.",
				MarkdownDescription: "Define a description for the local security group.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 48),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the retrieved local security group. This is the same as the SID.",
				MarkdownDescription: "The ID of the retrieved local security group. This is the same as the SID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Define the name for the local security group.",
				MarkdownDescription: "Define the name for the local security group.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"sid": schema.StringAttribute{
				Computed:            true,
				Description:         "The security ID of the local security group.",
				MarkdownDescription: "The security ID of the local security group.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

type LocalGroupModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Sid         types.String `tfsdk:"sid"`
}
