// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package local_datasources

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func LocalGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the local security group.",
				MarkdownDescription: "The description of the local security group.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the retrieved local security group. This is the same as the SID.",
				MarkdownDescription: "The ID of the retrieved local security group. This is the same as the SID.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Description:         "Define the name of the local security group.",
				MarkdownDescription: "Define the name of the local security group.",
			},
			"sid": schema.StringAttribute{
				Optional:            true,
				Description:         "Define the security ID of the local security group.",
				MarkdownDescription: "Define the security ID of the local security group.",
			},
		},
	}
}

type LocalGroupModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Sid         types.String `tfsdk:"sid"`
}
